version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: description
        no_empty:
          enabled: true
          message: 'Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.'
    pass:
      - do: labels
        labels: [ 'alltestspassed' ]
      - do: comment
        payload:
          body: 'New comment from mergeable'
